services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "33124:33124"
    environment:
      POSTGRES_USER: "jaw"
      POSTGRES_PASSWORD: "crabchat"
      POSTGRES_DB: "jawcrabchat"
    logging:
      options:
        max-size: "10m"
    command: [ "postgres", "-c", "log_statement=all", "-p", "33124"]

volumes:
  postgres_data: